### PR TITLE
Feature/stop

### PR DESCRIPTION
**Pull request by cescoferraro**
Add task stop action. And helps with #63

### CODE REVIEW

**Comment by cescoferraro** [comment]
jobs depends on images, so I thought that if we remove jobs first then dobi would not build the images again to remove a given job. I am wrong, somewhy dobi build images before removing. 


Test with the latest commit
```

meta:
    project: dobi
    default: all

mount=source:
    bind: .
    path: /go/src/github.com/dnephin/dobi


image=builder:
    image: dobi-dev
    context: dockerfiles/
    dockerfile: Dockerfile.build


job=watch:
    use: builder
    mounts: [source]
    command: script/watch
    interactive: true
    description: "Watch for code changes and run the unit tests"


cescoferraro@desktop: ~/code/go/src/github.com/dnephin/dobi on feature/stop [!]
$ go run main.go autoclean
[job:rm watch] {[]} Removed
[WARN] [mount:rm source] .:/go/src/github.com/dnephin/dobi Bind mounts are not removable
[WARN] [mount:rm source] .:/go/src/github.com/dnephin/dobi Bind mounts are not removable
[image:rm builder] dobi-dev Removed
Step 1 : FROM golang:1.7-alpine
 ---> 4e874ba52406
Step 2 : RUN apk add -U git bash curl tree
 ---> Using cache
 ---> 4e330f821d16
Step 3 : RUN export GLIDE=v0.12.3;         export SRC=https://github.com/Masterminds/glide/releases/download/;         curl -sL ${SRC}/${GLIDE}/glide-${GLIDE}-linux-amd64.tar.gz |         tar -xz linux-amd64/glide &&         mv linux-amd64/glide /usr/bin/glide &&         chmod +x /usr/bin/glide
 ---> Using cache
 ---> b354118480e9
Step 4 : RUN go get github.com/dnephin/filewatcher &&         cp /go/bin/filewatcher /usr/bin/ &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> 9cac65554acc
Step 5 : RUN go get github.com/mitchellh/gox &&         cp /go/bin/gox /usr/bin &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> d966a8394644
Step 6 : RUN go get github.com/golang/mock/mockgen &&         cp /go/bin/mockgen /usr/bin &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Using cache
 ---> d0636dec8fc2
Step 7 : WORKDIR /go/src/github.com/dnephin/dobi
 ---> Using cache
 ---> bc9911b6446a
Step 8 : ENV PS1 "# "
 ---> Using cache
 ---> b7571fd2742b
Step 9 : ENV CGO_ENABLED 0
 ---> Using cache
 ---> a8e94fe57280
Successfully built a8e94fe57280
[image:build builder] dobi-dev Created
[job:stop watch] {[]} Container dobi-cescoferraro-watch is not running
[job:rm watch] {[]} Removed
[image:rm builder] dobi-dev Removed

```

**Comment by dnephin** [comment]
>  so I thought that if we remove jobs first then dobi would not build the images again to remove a given job. I am wrong, somewhy dobi build images before removing.

That sounds like a bug. `job:rm` shouldn't depend on anything.

**Comment by dnephin** [comment]
Instead of adding a `stop` action I wonder if we can just attempt a stop before the remove, and ignore any errors?

**Comment by dnephin** [comment]
`job:rm` now does a force remove (#84), so it will kill the container before removing it.

Do you think we still need this stop action?

**Comment by cescoferraro** [comment]
Don't think so. Haven't tested the force remove thing yet though

**Pull request closed without merging**
