### PR TITLE
Feature/non root user

### LINKED ISSUE #7: Run task as non-root
Is there any way to get a Run task to execute as non-root? Currently, there doesn't appear to be a way to set the user for the run task like you can with docker via the `-u` command. I have tried setting the USER value in my Dockerfile but the run task still seems to execute as root.

### PR DESCRIPTION
**Pull request by cescoferraro**
Fixes #7 
Fixed problems also raised on #34 
@dnephin i seems that this is all there is to it.

Bumped golang version to 1.7.1 to make sure dobi users do not face [this](https://github.com/golang/go/issues/16739) issue that prevents it from resolving DNS .local domains.

also changed the name of a variable called image to avoid name collision with the image package

### CODE REVIEW

**Comment by dnephin** [comment]
Thanks! This looks good, I just made a couple small changes:
* removed the whitespace commit
* changed the `golang` image to `1.7-alpine`. This tag actually points at the same thing as `1.7.1-alpine` right now, but if  a 1.7.2 is released, it will be updated to point at that. See https://hub.docker.com/r/library/golang/
* restored the `.gitignore`. If you need to exclude editor files there are two better options for that. You can use [a global user defined `.gitignore`](https://help.github.com/articles/ignoring-files/#create-a-global-gitignore), or you can set it by project in `.git/info/exclude`

Once the tests pass I will merge.

**Comment by cescoferraro** [comment]
@dnephin I started working on the env resource. Will see how that goes, hopefully I get the hang of Dobi. I am pretty sure 1.0 will be dope 👌

**Comment by dnephin** [comment]
Ok cool. Are you working from my branch https://github.com/dnephin/dobi/tree/add-env-resource ? I think the `tform` framework for transforming the types isn't working for nested types yet. 

I was going to try to work on it a bit today, but if you're working on it, I can pick up a different issue.

If you'd like to chat in more real-time, I set up https://gitter.im/dnephin-dobi/Lobby for talking about the project.

**Comment by cescoferraro** [comment]
@dnephin I pulled that branch, and started playing around. Keep your awesome work, I will probably need to run some errands in a while.  Will join the Gitter!

**Pull request merged**
