### PR TITLE
Fix registry auth

### LINKED ISSUE #32: image:push authentication required
```bash
cesco@cesco-desktop: ~/code/go/src/bitbucket.org/cescoferraro/api on develop [+$]
$ VERSION=0.1.2 dobi  production:push
[WARN] Missing auth config for "https://golang/v1"
1.7.1-alpine: Pulling from library/golang
Digest: sha256:03ca8be2e13e3f83af9ce3fa181f88bddd39e83f1d2714ae7153620e9f051069
Status: Image is up to date for golang:1.7.1-alpine
[image:pull base] golang Pulled
[job:run binary] go build src/backend/api.go Start
[job:run binary] go build src/backend/api.go Done
Step 1 : FROM alpine:3.4
 ---> ee4603260daa
Step 2 : RUN apk add --no-cache ca-certificates apache2-utils
 ---> Using cache
 ---> 45118353fd77
Step 3 : ADD ./api /srv/app/api
 ---> Using cache
 ---> b53fd7b4f556
Step 4 : WORKDIR /srv/app
 ---> Using cache
 ---> a4d7f6a52822
Step 5 : CMD ./api runserver
 ---> Using cache
 ---> 94d98e1b5743
Step 6 : EXPOSE 9000
 ---> Using cache
 ---> 11fddc5aa441
Successfully built 11fddc5aa441
[image:build production] cescoferraro/api Created
[image:tag production] cescoferraro/api Tagged
[WARN] Missing auth config for "https://cescoferraro/v1"
The push refers to a repository [docker.io/cescoferraro/api]
328ac6e90ae9: Preparing 
b4b945d9e06c: Preparing 
9007f5987db3: Preparing 
[ERROR] Failed to execute task "production:push": unauthorized: authentication required
cesco@cesco-desktop: ~/code/go/src/bitbucket.org/cescoferraro/api on develop [+$]
$ docker push cescoferraro/api:v0.1.2
328ac6e90ae9: Pushed 
328ac6e90ae9: Pushing [===================================>               ] 11.14 MB/15.65 MB
b4b945d9e06c: Layer already exists 
v0.1.2: digest: sha256:7f551ac2ac64ba3535eaef411c0c4fd6ba729351ee83ff1b886ad8b48f23aa36 size: 949
```

### dobi.yaml

```
meta:
    project: api
    default: production

mount=source:
    bind: .
    path: /go/src/bitbucket.org/cescoferraro/api

image=base:
    image: golang
    tags: [1.7.1-alpine]
    pull: "always"

job=binary:
    use: base
    mounts: [source]
    command: go build src/backend/api.go
    working-dir: /go/src/bitbucket.org/cescoferraro/api
    description: "Build the static binary"

image=production:
    image: cescoferraro/api
    tags: ["v{env.VERSION}"]
    dockerfile: docker/Dockerfile.prod
    depends: [binary]
    description: "Production Image"
```

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #32

@cescoferraro are you able to build this branch and try it out?

It seems to work for me on both private hub repos and private quay.io repos. I'm not sure if there is any variation in the contents of the docker config file. Mine might be using a legay url for the default.

### CODE REVIEW

**Comment by cescoferraro** [comment]
@dnephin I will! Just a sec

**Comment by cescoferraro** [comment]
@dnephin It works now!  But I got a question. Are there any plans on a deploy resource?
I found Dobi while on the process of making all my go development inside docker containers as well as deploying those containers to Kubernetes and dobi seems like the perfect replacement for my old setup, Makefile+docker-compose. Maybe Docker-machines/swarm or even Kubernetes? I plan to help you as much as possible as soon as I figure out how things work.

**Comment by dnephin** [comment]
Yes! I think a deployment resource would fit really well. I've been waiting a bit on [docker deploy](https://github.com/docker/docker/issues/26876) to make it out of experimental so that API could be used to deploy to docker swarm mode.

I think other deployment types could be interesting as well.  One thing I'm not sure about is a good way to have the deploy task target a different `DOCKER_HOST`. 

For now, I think one method is just to create a `job` that does the deployment from a container.

**Comment by cescoferraro** [comment]
@dnephin docker deploy is a huge step to docker! Glad to know!
I am taking the job route for now! :+1:

**Comment by cescoferraro** [comment]
@dnephin I am using this docker image to make kubectl run inside a container.
https://github.com/wernight/docker-kubectl
I think I would need to add a user field to the job resource just like compose
https://docs.docker.com/compose/compose-file/#/cpushares-cpuquota-cpuset-domainname-hostname-ipc-macaddress-memlimit-memswaplimit-privileged-readonly-restart-shmsize-stdinopen-tty-user-workingdir

**Comment by dnephin** [comment]
Cool, #7 is the issue for adding the user field. Would you be interested in contributing?

**Pull request merged**
